[package]
name = "loot_box_v2"
edition = "2024"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }

[addresses]
loot_box_v2 = "0x01359f04eea1ed67e698794f092d280e23ced49ff66e24956c18e31e9e33ca0c"